// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

// import 'examples/lib/llm.omc';
let MODEL = "claude-opus-4-5";
let GENERATIONS = 4;
function extract_code(text) {
  if (omc.str_contains(text, "```omc")) {
    let parts = omc.str_split(text, "```omc");
    let after = parts[1];
    let end = omc.str_split(after, "```");
    return omc.str_trim(end[0]);
  }
  if (omc.str_contains(text, "```")) {
    let parts = omc.str_split(text, "```");
    if ((omc.arr_len(parts) >= 3)) {
      return omc.str_trim(parts[1]);
    }
  }
  return omc.str_trim(text);
}
function measure_code(code) {
  let lines = omc.str_split(code, "\n");
  let line_count = omc.arr_len(lines);
  let fn_count = 0;
  let loop_count = 0;
  let i = 0;
  while ((i < line_count)) {
    let line = omc.str_trim(lines[i]);
    if (str_starts_with(line, "fn ")) {
      fn_count = (fn_count + 1);
    }
    if (str_starts_with(line, "while ")) {
      loop_count = (loop_count + 1);
    }
    i = (i + 1);
  }
  return {lines: line_count, functions: fn_count, loops: loop_count};
}
function safe_run(code, test_input) {
  let test_code = str_concat(code, "\n", test_input);
  let result = eval_omc(test_code);
  return {ok: true, result: result};
}
function code_gen_loop(task_description, eval_prompt_template, generations) {
  let sys = str_concat("You write clean, idiomatic OMC code. Rules:\n", "- h varname = value for bindings\n", "- fn name(args) { body } for functions\n", "- while condition { body } for loops\n", "- arr_push(arr, val), arr_len(arr), arr_slice(arr, start, end) for arrays\n", "- str_concat(a, b, ...) for string concat\n", "- Return ONLY the OMC code, no fences or explanation.");
  omc.print(str_concat("Task: ", task_description));
  omc.print("");
  let history = [];
  let current_code = llm_call(str_concat("Write OMC code for: ", task_description), MODEL, sys);
  current_code = extract_code(current_code);
  let gen = 0;
  while ((gen < generations)) {
    omc.print(str_concat("--- Generation ", to_string((gen + 1)), " ---"));
    let metrics = measure_code(current_code);
    omc.print(str_concat("  Lines: ", to_string(metrics["lines"]), " | Fns: ", to_string(metrics["functions"]), " | Loops: ", to_string(metrics["loops"])));
    let run_result = safe_run(current_code, "");
    let run_status = "ok";
    if ((!(run_result["ok"]))) {
      run_status = to_string(run_result["error"]);
    }
    omc.print(str_concat("  Run status: ", run_status));
    omc.arr_push(history, {gen: (gen + 1), code: current_code, metrics: metrics, status: run_status});
    if (((gen + 1) >= generations)) {
      break;
    }
    let improve_prompt = omc.str_replace(eval_prompt_template, "{{CODE}}", current_code);
    let improved = llm_call(improve_prompt, MODEL, sys);
    current_code = extract_code(improved);
    gen = (gen + 1);
  }
  return {code: current_code, history: history, generations: generations};
}
omc.print("=== Task 1: Sorting Algorithm ===");
let sort_improve = str_concat("Improve this OMC sorting implementation. Make it more efficient and readable.\n\n", "Current code:\n{{CODE}}\n\n", "Return only the improved OMC code.");
let sort_result = code_gen_loop("Implement merge sort that returns a sorted copy of an integer array.", sort_improve, GENERATIONS);
omc.print(str_concat("Final code (", to_string(omc.arr_len(omc.str_split(sort_result["code"], "\n"))), " lines)"));
omc.print("");
omc.print("=== Task 2: Word Counter ===");
let word_improve = str_concat("Improve this OMC word counter. Add better punctuation handling and return top-N words.\n\n", "Current code:\n{{CODE}}\n\n", "Return only the improved OMC code.");
let wc_result = code_gen_loop("Count word frequencies in a string and return a dict of {word: count}, lowercased, punctuation stripped.", word_improve, GENERATIONS);
omc.print(str_concat("Final code (", to_string(omc.arr_len(omc.str_split(wc_result["code"], "\n"))), " lines)"));
omc.print("");
omc.print("=== Task 3: Statistics Library ===");
let stats_improve = str_concat("Improve this OMC stats library. Add median, mode, and standard deviation.\n\n", "Current code:\n{{CODE}}\n\n", "Return only the improved OMC code.");
let stats_result = code_gen_loop("Write mean(arr) and variance(arr) functions for a list of numbers.", stats_improve, GENERATIONS);
omc.print(str_concat("Final code (", to_string(omc.arr_len(omc.str_split(stats_result["code"], "\n"))), " lines)"));
omc.print("");
omc.print("=== Code Gen Loop Complete ===");
omc.print(str_concat("Ran ", to_string(GENERATIONS), " generations on each of 3 tasks."));
