// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

function show(label, v) {
  omc.print(concat_many(label, " = ", to_string(v)));
}
function section(name) {
  omc.print("");
  omc.print(concat_many("=== ", name, " ==="));
}
function make_msgs(n) {
  let msgs = [];
  let i = 0;
  while ((i < n)) {
    omc.arr_push(msgs, concat_many("msg-", to_string(i), ": some content about topic-", to_string((i % 8))));
    i = (i + 1);
  }
  return msgs;
}
function study(n) {
  let msgs = make_msgs(n);
  let before = omc.arr_len(msgs);
  let k = omc_m3_spawn_count(n);
  let specs = omc_context_compress(msgs);
  let after = omc.arr_len(specs);
  let ratio = (before / after);
  omc.print(concat_many("  N=", to_string(n), "  M3=", to_string(k), "  → ", to_string(after), " specialists", "  (compression ratio ", to_string(ratio), "×)"));
}
function main() {
  omc.print("=== Context compression via ONN self-instantiation ===");
  omc.print("");
  omc.print("Hermes ONN claim: any N items fold to M3(N) ~ O(log_phi-pi-fib N)");
  omc.print("specialists. Each holds phi-resonance-weighted summary statistics");
  omc.print("(mu, sigma, dominant Fibonacci attractor) of one wave of the input.");
  omc.print("");
  omc.print("Compression curve:");
  study(10);
  study(50);
  study(100);
  study(500);
  study(1000);
  study(5000);
  study(10000);
  omc.print("");
  omc.print("=== Inspect a single specialist ===");
  let msgs = make_msgs(50);
  let specs = omc_context_compress(msgs);
  omc.print(concat_many("50 messages → ", to_string(omc.arr_len(specs)), " specialists"));
  let first = arr_get(specs, 0);
  show("  fold_index        ", omc.dict_get(first, "fold_index"));
  show("  items in this spec", omc.dict_get(first, "item_count"));
  show("  mu (mean res)     ", omc.dict_get(first, "mu"));
  show("  sigma             ", omc.dict_get(first, "sigma"));
  show("  dominant_attractor", omc.dict_get(first, "dominant_attractor"));
  show("  resonance         ", omc.dict_get(first, "resonance"));
  show("  summary (truncated)", omc.dict_get(first, "summary"));
  section("Fold-back into a parent state");
  let parent_mu = 0.5;
  let parent_sigma = 0.1;
  let parent_turn = 0;
  let folded = omc_fold_back(parent_mu, parent_sigma, parent_turn, specs);
  show("  new mu              ", omc.dict_get(folded, "mu"));
  show("  new sigma           ", omc.dict_get(folded, "sigma"));
  show("  new turn_count      ", omc.dict_get(folded, "turn_count"));
  show("  dominant_attractor  ", omc.dict_get(folded, "dominant_attractor"));
  show("  num_specialists     ", omc.dict_get(folded, "num_specialists_folded"));
  omc.print("");
  omc.print("=== Practical implication ===");
  omc.print("Instead of dropping old conversation history, fold every");
  omc.print("100-message window into specialists and pass forward only the");
  omc.print("specialist dicts. Conversation memory becomes substrate-stable");
  omc.print("statistics, not raw bytes. The 'context problem' becomes a");
  omc.print("compression problem.");
}
main();
