// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

// import 'examples/lib/llm.omc';
// import * as cache from 'examples/lib/cache.omc';
let MODEL = "claude-opus-4-5";
let MEMO_CACHE = cache.lru_new(256);
function omc_ask(prompt) {
  let sys = "You are an expert OMC programmer. Output only valid OMC code, no markdown, no explanation.";
  return llm_call(prompt, MODEL, sys);
}
function strip_fences(text) {
  if (omc.str_contains(text, "```omc")) {
    let a = omc.str_split(text, "```omc");
    let b = omc.str_split(a[1], "```");
    return omc.str_trim(b[0]);
  }
  if (omc.str_contains(text, "```")) {
    let a = omc.str_split(text, "```");
    if ((omc.arr_len(a) >= 3)) {
      return omc.str_trim(a[1]);
    }
  }
  return omc.str_trim(text);
}
function run_code(code) {
  let result = eval_omc(code);
  return {ok: true, value: result};
}
function improve_once(code, goal) {
  let prompt = str_concat("Improve this OMC code to better achieve: ", goal, "\n\n", "Current code:\n", code, "\n\n", "Return only the improved code.");
  return strip_fences(omc_ask(prompt));
}
function critique(code, goal) {
  let prompt = str_concat("Analyze this OMC code for: ", goal, "\n\n", "Code:\n", code, "\n\n", "List exactly 3 specific improvements. Be terse.");
  return llm_call(prompt, MODEL, null);
}
function apply_critique(code, critique_text) {
  let prompt = str_concat("Apply these improvements to the OMC code:\n\n", "Code:\n", code, "\n\n", "Improvements:\n", critique_text, "\n\n", "Return only the improved OMC code.");
  return strip_fences(omc_ask(prompt));
}
function improve_to_convergence(code, goal, max_rounds) {
  let rounds = max_rounds;
  if ((rounds === null)) {
    rounds = 3;
  }
  let cache_key = str_concat(code, "|", goal);
  let cached = cache.lru_get(MEMO_CACHE, cache_key);
  if ((cached !== null)) {
    return cached;
  }
  let current = code;
  let trace = [{round: 0, code: current}];
  let r = 0;
  while ((r < rounds)) {
    let criticism = critique(current, goal);
    let improved = apply_critique(current, criticism);
    if ((improved === current)) {
      omc.print(str_concat("  Converged at round ", to_string((r + 1))));
      break;
    }
    current = improved;
    omc.arr_push(trace, {round: (r + 1), code: current, critique: criticism});
    r = (r + 1);
  }
  let result = {code: current, rounds: r, trace: trace};
  cache.lru_put(MEMO_CACHE, cache_key, result);
  return result;
}
function meta_improve(target_code, target_goal, meta_rounds) {
  let mr = meta_rounds;
  if ((mr === null)) {
    mr = 2;
  }
  let improver_goal = "An OMC function improve_fn(code, goal) that calls llm_call to improve code";
  let improver_template = str_concat("fn improve_fn(code, goal) {\n", "    h prompt = str_concat(\"Improve this OMC code for \", goal, \":\\n\", code)\n", "    h improved = llm_call(prompt, null, \"Write only OMC code, no explanation.\")\n", "    return improved\n", "}");
  omc.print("  Meta: improving the improver...");
  let improver_result = improve_to_convergence(improver_template, improver_goal, mr);
  let best_improver = improver_result["code"];
  omc.print("  Meta: running improved improver on target...");
  let improvement_code = str_concat(best_improver, "\n\n", "improve_fn(", json_stringify(target_code), ", ", json_stringify(target_goal), ")");
  let meta_result = run_code(improvement_code);
  let final_code = target_code;
  if ((meta_result["ok"] && (omc.type_of(meta_result["value"]) === "string"))) {
    final_code = strip_fences(meta_result["value"]);
  }
  return {code: final_code, improver: best_improver, meta_rounds: mr};
}
let programs = [{name: "Binary Search", code: "fn bsearch(arr, target) {\n    h lo = 0\n    h hi = arr_len(arr) - 1\n    while lo <= hi {\n        h mid = (lo + hi) / 2\n        if arr[mid] == target { return mid }\n        if arr[mid] < target { lo = mid + 1 }\n        else { hi = mid - 1 }\n    }\n    return -1\n}", goal: "Make binary search handle edge cases: empty array, single element, duplicates. Add early-exit optimization."}, {name: "String Reverser", code: "fn rev_str(s) {\n    h out = \"\"\n    h i = str_len(s) - 1\n    while i >= 0 {\n        out = str_concat(out, str_slice(s, i, i + 1))\n        i -= 1\n}\n    return out\n}", goal: "Make string reversal handle UTF-8 correctly and add word-reversal mode."}];
omc.print("=== Recursive Self-Improvement Orchestrator ===");
omc.print(str_concat("Model: ", MODEL));
omc.print("");
let i = 0;
while ((i < omc.arr_len(programs))) {
  let prog = programs[i];
  omc.print(str_concat("--- Improving: ", prog["name"], " ---"));
  omc.print(str_concat("Goal: ", prog["goal"]));
  omc.print("");
  omc.print("Pass 1: Direct improvement...");
  let direct = improve_to_convergence(prog["code"], prog["goal"], 2);
  omc.print(str_concat("  Done in ", to_string(direct["rounds"]), " rounds"));
  omc.print("Pass 2: Meta-improvement (improve the improver)...");
  let meta = meta_improve(direct["code"], prog["goal"], 1);
  omc.print("  Meta-improvement complete");
  let final_lines = omc.arr_len(omc.str_split(meta["code"], "\n"));
  omc.print(str_concat("  Final code: ", to_string(final_lines), " lines"));
  omc.print("");
  i = (i + 1);
}
omc.print("=== Recursive improvement complete ===");
omc.print("The improver improved itself, then improved the programs.");
omc.print("OMC writing OMC that writes OMC.");
