// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

// import 'examples/lib/llm.omc';
// import 'examples/lib/cache.omc';
let MODEL = "claude-opus-4-5";
let MAX_REPAIR_ATTEMPTS = 5;
let SOLUTION_CACHE = lru_new(100);
function extract_omc_code(text) {
  if (omc.str_contains(text, "```omc")) {
    let parts = omc.str_split(text, "```omc");
    let after = parts[1];
    let end_parts = omc.str_split(after, "```");
    return omc.str_trim(end_parts[0]);
  }
  if (omc.str_contains(text, "```")) {
    let parts = omc.str_split(text, "```");
    if ((omc.arr_len(parts) >= 3)) {
      return omc.str_trim(parts[1]);
    }
  }
  return omc.str_trim(text);
}
function safe_eval(code) {
  let result = eval_omc(code);
  return {ok: true, value: result, error: null};
}
function run_test(code, test_case) {
  let full_code = str_concat(code, "\n", "h __test_input = ", json_stringify(test_case["input"]), "\n", "h __test_result = ", test_case["call"], "(__test_input)\n", "__test_result");
  let result = safe_eval(full_code);
  if ((!(result["ok"]))) {
    return {passed: false, error: result["error"], expected: test_case["expected"], got: null};
  }
  let passed = (result["value"] === test_case["expected"]);
  return {passed: passed, expected: test_case["expected"], got: result["value"], error: null};
}
function run_all_tests(code, tests) {
  let failures = [];
  let i = 0;
  while ((i < omc.arr_len(tests))) {
    let r = run_test(code, tests[i]);
    if ((!(r["passed"]))) {
      omc.arr_push(failures, {test_idx: i, expected: r["expected"], got: r["got"], error: r["error"]});
    }
    i = (i + 1);
  }
  return failures;
}
function generate_solution(problem, tests) {
  let cached = lru_get(SOLUTION_CACHE, problem);
  if ((cached !== null)) {
    omc.print(str_concat("[cache hit] ", problem));
    return cached;
  }
  let sys = str_concat("You are an expert OMC (OmniMCode) programmer. Write clean, correct OMC code.\n", "Rules:\n", "- Use fn to define functions, h for variable binding\n", "- Use arr_push, arr_len, arr_slice for arrays\n", "- Use dict_has, dict_keys for dicts\n", "- Use str_concat, str_split, str_len, str_contains for strings\n", "- Use while loops (no for-in)\n", "- Return values explicitly with return\n", "- No imports needed for basic builtins\n", "Output ONLY the OMC code, no explanation, no markdown fences.");
  let prompt = str_concat("Write OMC code for this task:\n\n", problem);
  let code = llm_call(prompt, MODEL, sys);
  code = extract_omc_code(code);
  let attempt = 0;
  while ((attempt < MAX_REPAIR_ATTEMPTS)) {
    let failures = run_all_tests(code, tests);
    if ((omc.arr_len(failures) === 0)) {
      lru_put(SOLUTION_CACHE, problem, code);
      return {code: code, attempts: (attempt + 1), solved: true};
    }
    let failure_report = "Failures:\n";
    let fi = 0;
    while ((fi < omc.arr_len(failures))) {
      let f = failures[fi];
      failure_report = str_concat(failure_report, "  Test ", to_string(f["test_idx"]), ": expected=", to_string(f["expected"]), " got=", to_string(f["got"]));
      if ((f["error"] !== null)) {
        failure_report = str_concat(failure_report, " error=", to_string(f["error"]));
      }
      failure_report = str_concat(failure_report, "\n");
      fi = (fi + 1);
    }
    let fix_prompt = str_concat("This OMC code has test failures. Fix ALL of them.\n\n", "Code:\n", code, "\n\n", failure_report, "\nReturn ONLY the corrected OMC code.");
    let fixed = llm_call(fix_prompt, MODEL, sys);
    code = extract_omc_code(fixed);
    attempt = (attempt + 1);
  }
  return {code: code, attempts: MAX_REPAIR_ATTEMPTS, solved: false};
}
let PROBLEMS = [{name: "fizzbuzz", description: "Write a function fizzbuzz(n) that returns 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if by 15, else the number as string.", tests: [{input: 3, call: "fizzbuzz", expected: "Fizz"}, {input: 5, call: "fizzbuzz", expected: "Buzz"}, {input: 15, call: "fizzbuzz", expected: "FizzBuzz"}, {input: 7, call: "fizzbuzz", expected: "7"}]}, {name: "fibonacci", description: "Write a function fib(n) that returns the nth Fibonacci number (0-indexed: fib(0)=0, fib(1)=1, fib(2)=1, fib(6)=8).", tests: [{input: 0, call: "fib", expected: 0}, {input: 1, call: "fib", expected: 1}, {input: 6, call: "fib", expected: 8}, {input: 10, call: "fib", expected: 55}]}, {name: "palindrome", description: "Write a function is_palindrome(s) that returns true if the string is a palindrome, false otherwise.", tests: [{input: "racecar", call: "is_palindrome", expected: true}, {input: "hello", call: "is_palindrome", expected: false}, {input: "a", call: "is_palindrome", expected: true}, {input: "abba", call: "is_palindrome", expected: true}]}, {name: "sum_array", description: "Write a function sum_arr(arr) that returns the sum of all numbers in the array.", tests: [{input: [1, 2, 3, 4, 5], call: "sum_arr", expected: 15}, {input: [], call: "sum_arr", expected: 0}, {input: [42], call: "sum_arr", expected: 42}]}];
omc.print("=== Self-Improving OMC Agent ===");
omc.print(str_concat("Model: ", MODEL, " | Max repairs: ", to_string(MAX_REPAIR_ATTEMPTS)));
omc.print("");
let results = [];
let i = 0;
while ((i < omc.arr_len(PROBLEMS))) {
  let problem = PROBLEMS[i];
  omc.print(str_concat("[", to_string((i + 1)), "/", to_string(omc.arr_len(PROBLEMS)), "] Solving: ", problem["name"]));
  let result = generate_solution(problem["description"], problem["tests"]);
  if (result["solved"]) {
    omc.print(str_concat("  ✓ SOLVED in ", to_string(result["attempts"]), " attempt(s)"));
  } else {
    omc.print(str_concat("  ✗ FAILED after ", to_string(result["attempts"]), " attempts"));
  }
  omc.arr_push(results, {name: problem["name"], solved: result["solved"], attempts: result["attempts"], code: result["code"]});
  i = (i + 1);
}
omc.print("");
omc.print("=== Results ===");
let solved_count = 0;
let ri = 0;
while ((ri < omc.arr_len(results))) {
  let r = results[ri];
  let status = "FAIL";
  if (r["solved"]) {
    status = "PASS";
    solved_count = (solved_count + 1);
  }
  omc.print(str_concat("  ", status, " ", r["name"], " (", to_string(r["attempts"]), " attempts)"));
  ri = (ri + 1);
}
omc.print(str_concat("\nSolved: ", to_string(solved_count), "/", to_string(omc.arr_len(results))));
