// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

omc.print("=== harmonic_checksum ===");
omc.print(harmonic_checksum("89"));
omc.print(harmonic_checksum("90"));
omc.print(harmonic_checksum("hello world"));
omc.print("");
omc.print("=== harmonic_write_file ===");
let path = "/tmp/omc_harmonic_test.txt";
let score1 = harmonic_write_file(path, "89 144 233");
omc.print(score1);
omc.print(file_exists(path));
let read1 = harmonic_read_file(path);
omc.print(arr_get(read1, 0));
omc.print(arr_get(read1, 1));
omc.print("");
omc.print("=== harmonic_sort ===");
let mixed = [100, 89, 50, 144, 7, 233, 99];
let sorted = harmonic_sort(mixed);
omc.print(arr_join(sorted, ","));
omc.print("");
omc.print("=== harmonic_split ===");
let text = "the quick brown fox jumps over the lazy dog and runs fast home now";
let chunks = harmonic_split(text);
omc.print(omc.arr_len(chunks));
let i = 0;
while ((i < omc.arr_len(chunks))) {
  omc.print(concat_many("  [", str_chars(arr_get(chunks, i)), " chars] ", arr_get(chunks, i)));
  i = (i + 1);
}
omc.print("");
omc.print("=== harmonic_partition ===");
let values = [1, 2, 4, 8, 9, 13, 14, 21, 22, 88, 89, 90];
let groups = harmonic_partition(values);
omc.print(omc.arr_len(groups));
let j = 0;
while ((j < omc.arr_len(groups))) {
  let grp = arr_get(groups, j);
  omc.print(concat_many("  group ", j, ": ", arr_join(grp, ",")));
  j = (j + 1);
}
omc.print("");
omc.print("=== Composing with first-class functions ===");
function near_fib(n) {
  return is_fibonacci(n);
}
let candidates = [13, 14, 21, 22, 34, 35, 55, 56, 89];
let fibs_only = omc.arr_filter(candidates, near_fib);
omc.print(arr_join(fibs_only, ","));
omc.print("");
omc.print("=== Done ===");
