// Generated by omcj — OMC to JavaScript transpiler
import * as omc from './omc-runtime.js';

// import 'examples/lib/tape.omc';
function rust_train(W1d, b1d, W2d, b2d, ids, steps) {
  let vocab = 3;
  let n_pairs = (omc.arr_len(ids) - 1);
  tape_reset();
  let W1 = tape_var(W1d);
  let b1 = tape_var(b1d);
  let W2 = tape_var(W2d);
  let b2 = tape_var(b2d);
  let lr = 0.05;
  let step = 0;
  let loss_val = 0.0;
  while ((step < steps)) {
    let k = (step - ((step / n_pairs) * n_pairs));
    let xr = [0.0, 0.0, 0.0];
    xr[arr_get(ids, k)] = 1.0;
    let tr = [0.0, 0.0, 0.0];
    tr[arr_get(ids, (k + 1))] = 1.0;
    let x = tape_const([xr]);
    let tgt = tape_const([tr]);
    let xW1 = tape_matmul(x, W1);
    let h1 = tape_add(xW1, b1);
    let r1 = tape_relu(h1);
    let xW2 = tape_matmul(r1, W2);
    let h2 = tape_add(xW2, b2);
    let diff = tape_sub(h2, tgt);
    let sq = tape_mul(diff, diff);
    let loss = tape_mean(sq);
    tape_backward(loss);
    tape_update(W1, lr);
    tape_update(b1, lr);
    tape_update(W2, lr);
    tape_update(b2, lr);
    loss_val = tape_value(loss);
    step = (step + 1);
  }
  return loss_val;
}
function _sgd_update(mat, grad, lr) {
  let rows = omc.arr_len(mat);
  let r = 0;
  while ((r < rows)) {
    let mr = arr_get(mat, r);
    let gr = arr_get(grad, r);
    let j = 0;
    while ((j < omc.arr_len(mr))) {
      mr[j] = (arr_get(mr, j) - (lr * arr_get(gr, j)));
      j = (j + 1);
    }
    r = (r + 1);
  }
}
function omc_train(W1d, b1d, W2d, b2d, ids, steps) {
  let n_pairs = (omc.arr_len(ids) - 1);
  let lr = 0.05;
  let step = 0;
  let loss_val = 0.0;
  while ((step < steps)) {
    let k = (step - ((step / n_pairs) * n_pairs));
    let xr = [0.0, 0.0, 0.0];
    xr[arr_get(ids, k)] = 1.0;
    let tr = [0.0, 0.0, 0.0];
    tr[arr_get(ids, (k + 1))] = 1.0;
    let tape = otape_new();
    let W1_id = otape_var(tape, W1d);
    let b1_id = otape_var(tape, b1d);
    let W2_id = otape_var(tape, W2d);
    let b2_id = otape_var(tape, b2d);
    let x = otape_const(tape, [xr]);
    let tgt = otape_const(tape, [tr]);
    let xW1 = otape_matmul(tape, x, W1_id);
    let h1 = otape_add(tape, xW1, b1_id);
    let r1 = otape_relu(tape, h1);
    let xW2 = otape_matmul(tape, r1, W2_id);
    let h2 = otape_add(tape, xW2, b2_id);
    let loss = otape_mse(tape, h2, tgt);
    otape_backward(tape, loss);
    _sgd_update(W1d, otape_grad(tape, W1_id), lr);
    _sgd_update(b1d, otape_grad(tape, b1_id), lr);
    _sgd_update(W2d, otape_grad(tape, W2_id), lr);
    _sgd_update(b2d, otape_grad(tape, b2_id), lr);
    let lv = otape_value(tape, loss);
    loss_val = arr_get(arr_get(lv, 0), 0);
    step = (step + 1);
  }
  return loss_val;
}
function main() {
  omc.print("=== OMC-tape correctness vs Rust tape ===");
  omc.print("");
  let ids = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2];
  let steps = 200;
  let seeds = [42, 7, 123];
  let ok = 1;
  let s = 0;
  while ((s < omc.arr_len(seeds))) {
    let seed = arr_get(seeds, s);
    let W1r = otape_random_matrix(3, 8, 0.5, seed);
    let W1d = omc.dict_get(W1r, "mat");
    let b1d = [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]];
    let W2r = otape_random_matrix(8, 3, 0.5, omc.dict_get(W1r, "seed"));
    let W2d = omc.dict_get(W2r, "mat");
    let b2d = [[0.0, 0.0, 0.0]];
    let W1r2 = otape_random_matrix(3, 8, 0.5, seed);
    let W1d2 = omc.dict_get(W1r2, "mat");
    let b1d2 = [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]];
    let W2r2 = otape_random_matrix(8, 3, 0.5, omc.dict_get(W1r2, "seed"));
    let W2d2 = omc.dict_get(W2r2, "mat");
    let b2d2 = [[0.0, 0.0, 0.0]];
    let t0 = time_ms();
    let rust_loss = rust_train(W1d, b1d, W2d, b2d, ids, steps);
    let t_rust = (time_ms() - t0);
    let t1 = time_ms();
    let omc_loss = omc_train(W1d2, b1d2, W2d2, b2d2, ids, steps);
    let t_omc = (time_ms() - t1);
    let diff = (rust_loss - omc_loss);
    if ((diff < 0.0)) {
      diff = (0.0 - diff);
    }
    let match_ok = 1;
    if ((diff > 0.005)) {
      match_ok = 0;
      ok = 0;
    }
    let status = "OK";
    if ((match_ok === 0)) {
      status = "MISMATCH";
    }
    omc.print(concat_many("seed ", to_string(seed), "  rust=", to_string(rust_loss), "  omc=", to_string(omc_loss), "  diff=", to_string(diff), "  [", status, "]", "  rust=", to_string(t_rust), "ms  omc=", to_string(t_omc), "ms"));
    s = (s + 1);
  }
  omc.print("");
  if ((ok === 1)) {
    omc.print("[PASS] OMC tape matches Rust tape on all seeds.");
    omc.print("       The OMC tensor engine produces identical gradients.");
  } else {
    omc.print("[FAIL] Loss diverged — check backward implementation.");
  }
}
main();
